# Generated by Django 4.0.5 on 2022-07-29 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, verbose_name='Айди пользователя')),
                ('username', models.CharField(blank=True, default='Отсутствует username', max_length=50, null=True, verbose_name='Имя пользователя')),
                ('role', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RoleCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('active_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_user', to='aviato.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='create_user', to='aviato.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=5000)),
                ('address', models.CharField(max_length=5000)),
                ('full_name', models.CharField(max_length=5000)),
                ('product', models.CharField(max_length=5000)),
                ('price', models.CharField(max_length=100000)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='Фото')),
                ('additional_information', models.CharField(max_length=6000, verbose_name='Доп. Информация')),
                ('count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(blank=True, default='Ожидание подтверждения', max_length=200, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drive_user', to='aviato.profile', verbose_name='Водитель который принял заказ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aviato.profile', verbose_name='Пользователь который добавил товар')),
            ],
        ),
    ]
