# Generated by Django 4.2 on 2023-04-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(blank=True, choices=[('Ожидает упаковки', 'Ожидает упаковки'), ('Отменен', 'Отменен'), ('Ожидает отправки', 'Ожидает отправки'), ('Передан логисту', 'Передан логисту'), ('Упакован', 'Упакован'), ('Передан диспетчеру', 'Передан диспетчеру'), ('Доставлен', 'Доставлен'), ('Фабричный брак', 'Фабричный брак'), ('Дорожный брак', 'Дорожный брак'), ('Ожидание подтверждения', 'Ожидание подтверждения'), ('В дороге', 'В дороге')], default='Ожидание подтверждения', max_length=200, null=True, verbose_name='Статус'),
        ),
    ]
