# Generated by Django 4.0.5 on 2022-07-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0003_remove_applications_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='location',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Локация водителя'),
        ),
    ]
