# Generated by Django 4.2 on 2023-04-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0003_applications_uniquekey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='address',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='note',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='price',
            field=models.CharField(blank=True, max_length=100000, null=True, verbose_name='Цена'),
        ),
    ]
