# Generated by Django 4.0.5 on 2022-07-29 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0004_applications_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'verbose_name': 'Заявки', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Аккаунты', 'verbose_name_plural': 'Аккаунты'},
        ),
        migrations.AlterModelOptions(
            name='rolecode',
            options={'verbose_name': 'Заявки', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='applications',
            name='address',
            field=models.CharField(max_length=5000, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='full_name',
            field=models.CharField(max_length=5000, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='note',
            field=models.CharField(max_length=5000, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='price',
            field=models.CharField(max_length=100000, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='product',
            field=models.CharField(max_length=5000, verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(blank=True, default='Ожидание подтверждения', max_length=200, null=True, verbose_name='Статус товара'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(default='', max_length=200, verbose_name='Роль пользователя'),
        ),
        migrations.AlterField(
            model_name='rolecode',
            name='active_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_user', to='aviato.profile', verbose_name='Пользоватлеь который активировал код'),
        ),
        migrations.AlterField(
            model_name='rolecode',
            name='code',
            field=models.CharField(max_length=200, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='rolecode',
            name='role',
            field=models.CharField(max_length=200, verbose_name='Роль которая выдается после активация кода'),
        ),
        migrations.AlterField(
            model_name='rolecode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='create_user', to='aviato.profile', verbose_name='Пользователь который создал код'),
        ),
    ]
