# Generated by Django 4.2 on 2023-04-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0004_alter_applications_address_alter_applications_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Айди пользователя'),
        ),
    ]
