# Generated by Django 4.0.5 on 2022-07-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0006_alter_rolecode_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='phone',
            field=models.CharField(default=1, max_length=100, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
