# Generated by Django 4.1.1 on 2023-04-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0007_alter_applications_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(blank=True, choices=[('Ожидает упаковки', 'Ожидает упаковки'), ('Отменен', 'Отменен'), ('Ожидает отправки', 'Ожидает отправки'), ('Передан логисту', 'Передан логисту'), ('Упакован', 'Упакован'), ('Передан диспетчеру', 'Передан диспетчеру'), ('Фабричный брак', 'Фабричный брак'), ('Дорожный брак', 'Дорожный брак'), ('Ожидание подтверждения', 'Ожидание подтверждения'), ('В дороге', 'В дороге'), ('Доставлен', 'Доставлен'), ('Подтверждена', 'Подтверждена'), ('Нет в наличии', 'Нет в наличии'), ('Приостановлено', 'Приостановлено')], default='Ожидание подтверждения', max_length=200, null=True, verbose_name='Статус'),
        ),
    ]
