# Generated by Django 4.0.5 on 2022-07-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0008_profile_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
    ]
