# Generated by Django 4.0.5 on 2022-07-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0009_alter_profile_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='time_update_location',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
    ]
