# Generated by Django 4.1.1 on 2023-04-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0009_alter_applications_status_alter_profile_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Роль не выдана', 'Роль не выдана'), ('Упаковщик-Логист', 'Упаковщик-Логист'), ('Снабженец', 'Снабженец'), ('Админ', 'Админ'), ('Менеджер', 'Менеджер'), ('Логист', 'Логист'), ('Оператор', 'Оператор'), ('Водитель', 'Водитель'), ('Упаковщик', 'Упаковщик')], default='', max_length=200, verbose_name='Роль пользователя'),
        ),
    ]
