# Generated by Django 4.1.1 on 2023-04-30 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0010_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='aviato.profile', verbose_name='Добавил'),
        ),
    ]
