# Generated by Django 4.0.5 on 2022-07-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0010_applications_time_update_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время создании заявки'),
        ),
    ]
