# Generated by Django 4.0.5 on 2022-08-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0011_applications_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='applications',
            name='time_update_location',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения локации'),
        ),
    ]
