# Generated by Django 4.0.5 on 2022-08-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0012_report_alter_applications_time_update_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='canceled_reason',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Причина отмены заказа'),
        ),
    ]
