# Generated by Django 4.0.5 on 2022-08-03 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0013_applications_canceled_reason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
