# Generated by Django 4.0.5 on 2022-08-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0014_delete_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='direction',
            field=models.CharField(default=1, max_length=400, verbose_name='Направление'),
            preserve_default=False,
        ),
    ]
