# Generated by Django 4.0.5 on 2022-08-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0015_applications_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='direction',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Направление'),
        ),
    ]
