# Generated by Django 4.0.5 on 2022-08-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0016_alter_applications_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='location_time',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Врея локация'),
        ),
    ]
