# Generated by Django 4.0.5 on 2022-08-09 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0017_applications_location_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='delivery_information',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Информация о доставке'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='canceled_reason',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Причина отмены'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drive_user', to='aviato.profile', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='location',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='location_time',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Время локации'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(blank=True, default='Ожидание подтверждения', max_length=200, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aviato.profile', verbose_name='Добавил'),
        ),
    ]
