# Generated by Django 4.0.5 on 2022-08-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0018_applications_delivery_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='create_time',
            field=models.DateField(auto_now=True, verbose_name='Время создания'),
        ),
    ]
