# Generated by Django 4.0.5 on 2022-08-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0019_alter_applications_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='bool_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
