# Generated by Django 4.1 on 2022-08-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0020_products_remove_applications_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='bool_status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Подт / Отм'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='aviato.products', verbose_name='Привязанный товар'),
        ),
    ]
