# Generated by Django 4.0.5 on 2022-08-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0020_applications_bool_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='checks_document',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Чек'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='bool_status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Подтвержден'),
        ),
    ]
