# Generated by Django 4.0.5 on 2022-08-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0021_applications_checks_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='opt_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Оптовая цена'),
        ),
    ]
