# Generated by Django 4.1 on 2022-08-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0021_alter_applications_bool_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='product',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Товар'),
        ),
    ]
