# Generated by Django 4.0.6 on 2022-08-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0023_alter_applications_bool_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(blank=True, choices=[('Ожидание подтверждения', 'Ожидание подтверждения'), ('Ожидание подтверждения', 'Ожидание подтверждения'), ('Ожидание подтверждения', 'Ожидание подтверждения')], default='Ожидание подтверждения', max_length=200, null=True, verbose_name='Статус'),
        ),
    ]
