# Generated by Django 4.0.5 on 2022-08-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0024_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
