# Generated by Django 4.0.6 on 2022-08-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0024_alter_applications_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(blank=True, choices=[('Подтвержден', 'Подтвержден'), ('Отменен', 'Отменен'), ('Передан упаковщику', 'Передан упаковщику'), ('Передан логисту', 'Передан логисту'), ('Упакован', 'Упакован'), ('Доставлен', 'Доставлен'), ('Фабричный брак', 'Фабричный брак'), ('Дорожный брак', 'Дорожный брак'), ('Ожидание подтверждения', 'Ожидание подтверждения')], default='Ожидание подтверждения', max_length=200, null=True, verbose_name='Статус'),
        ),
    ]
