# Generated by Django 4.0.5 on 2022-08-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0026_alter_products_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_percent',
            field=models.FloatField(default=5, verbose_name='2.5% От Суммы Товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='product_suum',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Сумма товара'),
        ),
    ]
