# Generated by Django 4.0.5 on 2022-08-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0027_products_product_percent_products_product_suum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='2.5% От Суммы Товара'),
        ),
    ]
