# Generated by Django 4.0.5 on 2022-08-11 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0029_remove_applications_photo_applications_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aviato.products', verbose_name='Привязанный товар'),
        ),
    ]
