# Generated by Django 4.0.5 on 2022-08-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0030_alter_applications_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='fake_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
