# Generated by Django 4.0.5 on 2022-08-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0031_products_fake_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
