# Generated by Django 4.0.5 on 2022-08-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0033_remove_applications_products_applications_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='count',
            field=models.CharField(max_length=1000000, verbose_name='Количество'),
        ),
    ]
