# Generated by Django 4.0.5 on 2022-08-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0034_alter_products_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
