# Generated by Django 4.0.5 on 2022-08-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0035_alter_products_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='bool_count',
            field=models.BooleanField(default=True, verbose_name='Хватает ли количество'),
        ),
    ]
